apiVersion: v1
kind: Pod
metadata:
  name: self-ballooning-test-pod
  labels:
    app: ubuntu
spec:
  containers:
    - name: self-ballooning-test-container
      image: ubuntu
      command:
        - "/bin/bash"
        - "-c"
        - |
          while true; do
            if [ -f /tmp/mt_mem_updown ]; then
              echo "File exists. Running your command..."
              # Replace the following line with the command you want to run if the file exists
              ./tmp/mt_mem_updown 8 2 10 500 10
              break
            else
              echo "File does not exist. Waiting..."
              sleep 10  # Adjust the interval as needed
            fi
          done
      resources:
        requests:
          cpu: "4"
          memory: "16Gi"
